print('=== Desafio 8 ===')
n = int(input('Digite uma distância em metros: '))
dam = (n / 10)
dm = (n * 10)
cm = (dm * 10)
mm = (cm * 10)
hm = (dam / 10)
km = (hm / 10)
print('A médida {}m corresponde a: \n {}km, \n {}hm, \n {}dam, \n {}dm, \n {}cm, \n {}mm'.format(n, km, hm, dam, dm, cm, mm))
